---
# Copyright 2016 University of Liverpool

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#  http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


- name: Determine if Java is already installed
  shell: which java
  register: oracle_java_task_installed
  ignore_errors: yes
  changed_when: False


- name: Set fact oracle_java_installed
  set_fact:
    oracle_java_installed={{ oracle_java_task_installed.rc == 0 }}
  when: oracle_java_task_installed is defined and oracle_java_task_installed.rc is defined
  changed_when: False
   

- name: Determine Java version
  shell: java -version 2>&1 | head -n 1 | awk '{ print $3 }' | awk -F '"' '{ print $2 }'
  when: oracle_java_installed is defined
  register: oracle_java_task_version
  changed_when: False


- name: Set fact oracle_java_installed_version
  set_fact:
    oracle_java_version_installed={{ oracle_java_task_version.stdout }}
  when: oracle_java_task_version is defined and oracle_java_task_version.stdout is defined
  changed_when: False
  
- debug: var=oracle_java_version_installed